version: '3.8'

services:
  magalu-notification-api:
    build: .
    container_name: magalu-notification-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db:5432/magalu_notification_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgresql-db
    networks:
      - magalu-network

  postgresql-db:
    image: postgres
    container_name: postgresql-db
    environment:
      POSTGRES_DB: magalu_notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - magalu-network

volumes:
  postgres-data:

networks:
  magalu-network:
    driver: bridge
